[package]
name = "jsonstat"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
strip = true # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true # This can remove dead code and often times reduces binary size.
codegen-units = 1 # Allow for maximum size reduction optimizations, but longer compile time.

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }